### PR TITLE
[#41] Updated to be upload with hexer app to hex.pm package manager 

### PR DESCRIPTION
**Pull request by davecaos**

### CODE REVIEW

**Comment by hcs42** [comment]
@davecaos (also @elbrujohalcon) I fixed the travis issue in https://github.com/esl/elarm/pull/43. Could you rebase your commit on the top of the master branch?

**Comment by davecaos** [comment]
I think this PR passed all checks https://travis-ci.org/esl/elarm/builds/100340784, but didn't update the state.

**Comment by hcs42** [comment]
Could you push this commit as the PR?
https://github.com/hcs42/elarm/commits/dave.41.upload.to.hex.pm

It will make for a cleaner git history, since it will be a single commit on the top of the current master branch, as opposed to the current "commit+merge commit" combination.

**Comment by hcs42** [comment]
@davecaos What do you think?

**Comment by elbrujohalcon** [comment]
@hcs42 didn't he do that already?

**Comment by hcs42** [comment]
> didn't he do that already?

No. Compare:

* https://github.com/esl/elarm/pull/42/commits
* https://github.com/hcs42/elarm/commits/dave.41.upload.to.hex.pm

**Comment by elbrujohalcon** [comment]
@hcs42 I see… let me try to work it out myself

**Comment by elbrujohalcon** [comment]
@davecaos you were basically missing a `git rebase master`

**Comment by elbrujohalcon** [comment]
@hcs42 check it out now, please

**Pull request merged**
